### ISSUE TITLE
Auto-discovery / Auto-clustering

### ISSUE THREAD

**Issue by testark** [erlio/vernemq#150]
It would be great to have auto-discovery / auto-clustering capabilities in VerneMQ. A discovery mechanism based on `etcd` or DNS would be great. It would also be great if nodes could auto-cluster themselves upon discovery. WDYT @ioolkos @dergraf ?

**Comment by testark** [comment]
( For my particular scenario I would benefit more from auto-clustering given a list of known nodes, but an auto-discovery mechanism may also come in handy for other users. )

**Comment by ioolkos** [comment]
Hi @testark, thanks for your initiative :)
Ok, let's say discovery (etcd or DNS) first. Can we define then, what component or functionality is actually missing in VerneMQ?
What kind of external tooling has to talk to VerneMQ in what way? (or vice versa)

**Comment by dergraf** [comment]
Closing due to inactivity, please reopen

**Comment by rokka-n** [comment]
Hi,

I've just looked into this. Discovery mechanism must not depend on particular KV backend. Nodes should discovery it's peers using some sort of gossip protocol. 

Using hardcoded IPs, which seems the case of how its designed at present moment, doesn't add much to clustering capabilities.

```
version: "2"

services:
  mqtt1.local:
    container_name: mqtt1.local
    image: erlio/docker-vernemq
    environment:
      DOCKER_VERNEMQ_LOG__CONSOLE__LEVEL: debug

  mqtt2.local:
    container_name: mqtt2.local
    image: erlio/docker-vernemq
    environment:
      DOCKER_VERNEMQ_DISCOVERY_NODE: 172.20.0.2
      DOCKER_VERNEMQ_LOG__CONSOLE__LEVEL: debug
    links:
      - mqtt1.local
```

DOCKER_VERNEMQ_DISCOVERY_NODE should be mqtt1.local for this simple example.
