### ISSUE TITLE
Websocket listener chokes on messages between 32 and 64 kB

### ISSUE THREAD

**Issue by trehn** [erlio/vernemq#592]
### Environment

- VerneMQ Version: 1.3.0
- OS: Docker

### Configuration

```
  mqtt:
    environment:
      - DOCKER_VERNEMQ_LISTENER__MAX_CONNECTIONS=96000
      - DOCKER_VERNEMQ_LISTENER__NR_OF_ACCEPTORS=100
      - DOCKER_VERNEMQ_MAX_CLIENT_ID_SIZE=32
      - DOCKER_VERNEMQ_MAX_MESSAGE_SIZE=524288
      - DOCKER_VERNEMQ_PERSISTENT_CLIENT_EXPIRATION=1h
      - DOCKER_VERNEMQ_PLUGINS__VMQ_ACL=off
      - DOCKER_VERNEMQ_PLUGINS__VMQ_DIVERSITY=on
      - DOCKER_VERNEMQ_PLUGINS__VMQ_PASSWD=off
      - DOCKER_VERNEMQ_VMQ_DIVERSITY__AUTH_REDIS__ENABLED=on
      - DOCKER_VERNEMQ_VMQ_DIVERSITY__REDIS__HOST=redis
    image: erlio/docker-vernemq:1.3.0
    ports:
      - "8081:8080"
    restart: always
    ulimits:
      nofile:
        soft: 100000
        hard: 100000
```

### Expected behavior

A client can send messages of any size up to MAX_MESSAGE_SIZE.

### Actual behaviour

When a client sends a message with a payload size >= 32671 bytes but <= 65446 bytes, the server closes the connection mid-transfer. Messages with a payload length of 65447 bytes (and above) or 
32670 bytes (and below) work as expected.

MQTT payload length | works?
------------------- | ------
...                 | yes   
32670               | yes   
32671               | no    
...                 | no    
65446               | no    
65447               | yes   
...                 | yes   

32671 = 32 * 1024 - 97
65446 = 64 * 1024 - 90

Yes, it's weird. To rule out a client-side issue, I looked at the exchange in Wireshark:

![Wireshark screenshot](https://user-images.githubusercontent.com/28724/35437771-2d2d1056-0294-11e8-87c4-44b0b0e943e6.png)

The IP starting with 10 is the client, IP starting with 35 is the server.

In line 27, the client starts sending the message, each packet being 1474 bytes long. In line 35, the server starts shutting down the websocket connection for no apparent reason, after receiving just 7 * 1474 = 10318 bytes.

I'm talking directly to VerneMQ without a (reverse) proxy or anything in between. This only happens when using the websocket listener, I was not able to observe any issues when talking plain MQTT over port 1883 using the same client and message sizes.

Nothing in logs.
